spring:
  application:
    name: Notification
  datasource:
    url: jdbc:mysql://notification-db:3306/notification_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL55Dialect
  kafka:
    consumer:
      bootstrap-servers: message-broker:29092
      group-id: notification-service
  zipkin:
    base-url: http://zipkin:9411
server:
  port: 8080
logging:
  level:
    org.apache.kafka: INFO #DEBUG