spring:
  application:
    name: User
  datasource:
    url: jdbc:mysql://user-db:3306/user_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL55Dialect
  kafka:
    consumer:
      bootstrap-servers: message-broker:29092
      group-id: user-service
    producer:
      bootstrap-servers: message-broker:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: "user-transaction"
  zipkin:
    base-url: http://zipkin:9411
server:
  port: 8080
logging:
  level:
    org.apache.kafka: INFO #DEBUG