server:
  port: 8000
event:
  command:
    url: http://localhost:8080
  query:
    url: http://localhost:8081
user:
  url: http://localhost:8082
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - gateway
spring:
  zipkin:
    base-url: http://localhost:9411
