spring:
  application:
    name: EventQuery
  datasource:
    url: jdbc:mysql://localhost:3307/event_query
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL55Dialect
server:
  port: 8081