PUT http://localhost:8080/event
Content-Type: application/json

{
  "aggregateID": "a7b21d7d-7776-47c6-b987-3410f0cda8f8",
  "time" : "2024-02-02T15:00:00.000+0100",
  "place" : "Test place",
  "capacity" : 100,
  "title" : "Robert!"
}