name: event-command-service build, test and deploy

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  mvn-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Compile and test with Maven
      run: |
        cd microservice/event-manager-parent/
        mvn -B -pl ./event/event-command-service --also-make clean verify -ntp
  docker-build:
    runs-on: ubuntu-latest
    needs: mvn-build-test
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./microservice/event-manager-parent/event/event-command-service/
          push: true
          tags: robertjuhas.com/event-command-service:latest
